# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example choc-corne nice_nano_v2 QWERTY vi mouse-move'
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["choc-corne_left","choc-corne_right"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y"]'
      branches: '["petejohanson/zmk/feat/pointers-move-scroll"]'
